---
title: "CellChat"
output: html_document
date: "2025-03-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load, echo = FALSE, warning = FALSE, message = FALSE}
suppressMessages(library(Seurat))
suppressMessages(library(ggplot2))
suppressMessages(library(cowplot))
suppressMessages(library(patchwork))
suppressMessages(library(data.table))
suppressMessages(library(viridis))
suppressMessages(library(dplyr))
suppressMessages(library(CellChat))
set.seed(626)
seu <- readRDS('../Data/OESTM_240225.rds')
sseu <- readRDS('../Data/Epi_Signature.rds')
```

```{r}
cc_colors <- c('DEN FB' = '#6FDADA',
               'Tumour FB' = '#E07F80',
               'Other' = '#9C80B2',
               'Tumour 12' = '#D7E5ED',
               'Tumour 1'= '#F6CBCB')


```

```{r}
C19 <- subset(seu,subset=Leiden_res.0.6 %in% c(19) & condition %in% c('Tumour','DEN'))
C19$cc_condition <- ifelse(seu$condition == 'Tumour','Tumour FB','DEN FB')
sseu$cc_condition <- sseu$tumour_groups
cseu <- merge(sseu,C19)
cseu <- JoinLayers(cseu)

unique(cseu$cc_condition)
cseu$cc_condition <- factor(cseu$cc_condition,levels = c("Tumour 12","Tumour 1","Other","DEN FB","Tumour FB"))
```

```{r}
#### Create a CellChat object ####
cellchat <- createCellChat(object = cseu, group.by = "cc_condition")
cellchat@DB <- CellChatDB.mouse 
```

```{r}
#### Identify Overexpressed Genes and Ligand-Receptor Pairs ####

cellchat <- subsetData(cellchat)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
```

```{r}
#### Calculate Communication Probabilities ####
cellchat <- computeCommunProb(cellchat)
cellchat <- filterCommunication(cellchat, min.cells = 10)
```

```{r}
#### Infer the communication network at the pathway level ####
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
```

```{r, fig.width=10,fig.height = 10, fig.wide = TRUE, fig.align = "center"}
groupSize <- as.numeric(table(cellchat@idents))
pdf('../Plots/CellChat/Interaction_circle.pdf',width = 10,height = 10)
par(mfrow = c(1,2), xpd=TRUE)
netVisual_circle(cellchat@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Number of interactions",color.use = cc_colors)
netVisual_circle(cellchat@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Interaction weights/strength",color.use = cc_colors)
dev.off()
```

```{r, fig.width=11,fig.height = 9, fig.wide = TRUE, fig.align = "center"}
mat <- cellchat@net$weight
pdf('../Plots/CellChat/Interaction_circle_individual.pdf',width = 10,height = 10)
par(mfrow = c(2,3), xpd=TRUE)
for (i in 1:nrow(mat)) {
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  mat2[i, ] <- mat[i, ]
  netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T,
                   edge.weight.max = max(mat), title.name = rownames(mat)[i],color.use = cc_colors)
}
dev.off()
```

```{r}
pathways.show <- 'EGF'
# Compute the network centrality scores
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP") 
netAnalysis_signalingRole_network(cellchat, signaling = pathways.show, width = 8, height = 2.5, font.size = 10,color.heatmap = 'BuGn',color.use = cc_colors)
```

Visualize the dominant senders (sources) and receivers (targets) in a 2D space
```{r,fig.width=5, fig.height=5}
# Signaling role analysis on the aggregated cell-cell communication network 
# from all signaling pathways
pdf('../Plots/CellChat/Signalling_Role_Scatter.pdf',width = 5,height = 5)
gg1 <- netAnalysis_signalingRole_scatter(cellchat,color.use = cc_colors)
gg1
dev.off()
```

```{r,fig.width=20, fig.height=20}
## Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
# 1. plot all pathways
pdf('../Plots/CellChat/Signalling_All_pathways.pdf',width = 20,height = 20)
ht1 <- netAnalysis_signalingRole_heatmap(cellchat, pattern = "outgoing",width = 15,height = 40,color.use = cc_colors)
ht2 <- netAnalysis_signalingRole_heatmap(cellchat, pattern = "incoming",width = 15,height = 40,color.use = cc_colors)
ht1 + ht2
dev.off()
```

```{r,fig.width=20, fig.height=10}
## Signaling role analysis on the cell-cell communication networks of interest
### 2. SET PATHWAYS 
# View enriched pathways
enriched.pathways <- cellchat@netP[["pathways"]]
enriched.pathways
pathways.show <- enriched.pathways[1:10]

pdf('../Plots/CellChat/Signalling_Top10_pathways.pdf',width = 20,height = 20)
ht1.s <- netAnalysis_signalingRole_heatmap(cellchat, signaling = pathways.show,
                                           pattern = "outgoing",width = 15,height = 15,color.use = cc_colors)
ht2.s <- netAnalysis_signalingRole_heatmap(cellchat, signaling = pathways.show,
                                           pattern = "incoming",width = 15,height = 15,color.use = cc_colors)
ht1.s + ht2.s
dev.off()

```

```{r}
### SET PATHWAYS 
pathways.show <- enriched.pathways # plot all enriched pathways
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP")
# ( 1 plot per pathway )
pdf('../Plots/Immune/CellChat/Signalling_IndividualPathways.pdf')
netAnalysis_signalingRole_network(cellchat, signaling = pathways.show, width = 8, height = 2.5, font.size = 10,color.use = cc_colors)
dev.off()
```

```{r}
pdf(file = '../Plots/CellChat/EGF_Violin.pdf',width = 7,height = 7)
plotGeneExpression(cellchat, signaling = "EGF", enriched.only = TRUE, type = "violin",
                   color.use = cc_colors,features = c('Areg','Hbegf','Egfr','Erbb2'))
dev.off()
```

```{r}
pdf(file = '../Plots/CellChat/FN1_Violin.pdf',width = 7,height = 7)
plotGeneExpression(cellchat, signaling = "FN1", enriched.only = TRUE, type = "violin",
                   color.use = cc_colors,features = c('Fn1','Itgav','Itga3','Itgb6'))
dev.off()
```
